services:
  api:
    image: geek-api:latest
    environment:
      PUID: ${PUID:?error}
      PGID: ${PGID:?error}
      TZ: ${TZ:?error}
      ConnectionStrings__DefaultConnection: "Server=${DB_HOST:?error};Database=${DB_DB:?error};User=${DB_USER:?error};Password=${DB_PASS:?error};"
      AppSettings__Token__Key: ${TOKEN_KEY:?error}
      AppSettings__Token__Expires: ${TOKEN_EXPIRES_HOURS:-24}
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`${TRAEFIK_HOST:?error}`)
      - traefik.http.routers.api.entrypoints=web
      - traefik.http.services.api.loadbalancer.server.port=8080
      - com.centurylinklabs.watchtower.enable=true
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      - db
    restart: always

  db:
    image: lscr.io/linuxserver/mariadb:latest
    ports:
      - "3306:3306"
    environment:
      PUID: ${PUID:?error}
      PGID: ${PGID:?error}
      TZ: ${TZ:?error}
      MYSQL_ROOT_PASSWORD: ${DB_PASS:?error}
    restart: always
  watchtower:
    image: containrrr/watchtower:latest
    environment:
      PUID: ${PUID:?error}
      PGID: ${PGID:?error}
      TZ: ${TZ:?error}
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_POLL_INTERVAL: 60
      WATCHTOWER_LABEL_ENABLE: true
      WATCHTOWER_REMOVE_VOLUMES: true
      WATCHTOWER_REVIVE_STOPPED: true
      WATCHTOWER_INCLUDE_STOPPED: true
      WATCHTOWER_ROLLING_RESTART: true
      WATCHTOWER_INCLUDE_RESTARTING: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
  reverse-proxy:
    image: traefik:v3.1
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --accesslog=true
      - --log.level=info
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TOKEN}
      - TUNNEL_LOGLEVEL=info
