version: '3.9'

services:
  db:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: db
    ports:
      - "3306:3306"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - MYSQL_ROOT_PASSWORD=toor
